# Generated by Django 4.1.3 on 2022-12-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('isFilm', models.IntegerField()),
                ('dateOfPurchase', models.DateTimeField()),
                ('isWorking', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('iso', models.IntegerField()),
                ('numOfImg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('filmend', models.DateTimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.camera')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.event')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.film')),
            ],
        ),
    ]
