# Generated by Django 4.1.3 on 2022-12-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_event_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
